import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft, GitPullRequest } from "lucide-react";
import { Badge, Button, Code, KV, Panel } from "@/components/ui";
import { Level } from "@/components/ui/domain";
import { detectionById, tenantById } from "@/lib/data";
import { fmtDateTime } from "@/lib/format";

const stateTone = { deployed: "signal", pending: "ember", failed: "flare", not_deployed: "muted" } as const;
const backendLabel = { spl: "Splunk SPL", eql: "Elastic EQL", lucene: "Lucene / KQL" };

export default async function DetectionDetail({ params }: PageProps<"/detections/[id]">) {
  const { id } = await params;
  const d = detectionById(id);
  if (!d) notFound();
  const t = d.tenantId ? tenantById(d.tenantId) : null;
  const canDeploy = d.backends.some((b) => b.state === "not_deployed" || b.state === "failed");
  return (
    <div>
      <Link href="/detections" className="text-[12.5px] text-muted hover:text-text inline-flex items-center gap-1 mb-4"><ChevronLeft size={14} /> Detections</Link>
      <div className="flex flex-wrap items-start justify-between gap-4 mb-6">
        <div>
          <div className="flex items-center gap-2 mb-2">{d.scope === "core" ? <Badge tone="cobalt">Core library</Badge> : <Badge>{t!.name}</Badge>}<Level level={d.level} /><span className="text-[12.5px] text-muted capitalize">{d.status}</span></div>
          <h1 className="text-[24px] font-semibold tracking-[-0.02em] leading-tight">{d.title}</h1>
        </div>
        <div className="flex gap-2">
          {d.pr && <Button><GitPullRequest size={14} /> PR #{d.pr}</Button>}
          {d.scope === "core" ? <Button variant="primary">Adopt for a tenant</Button> : canDeploy && <Link href="/approvals"><Button variant="primary">Request deploy</Button></Link>}
        </div>
      </div>
      <div className="grid lg:grid-cols-[1fr_340px] gap-6">
        <div className="space-y-6">
          <Panel title="Sigma source" meta={d.gitPath}><div className="px-4 pb-4"><Code>{d.sigma}</Code></div></Panel>
          <Panel title="Compiled output" meta="generated by pySigma on merge">
            <div className="px-4 pb-4 space-y-3">
              {d.backends.map((b) => (
                <div key={b.backend}>
                  <div className="flex items-center gap-2 mb-1.5 text-[12.5px]"><span className="font-medium">{backendLabel[b.backend]}</span><Badge tone={stateTone[b.state]}>{b.state.replace("_", " ")}</Badge>{b.at && <span className="text-faint">{fmtDateTime(b.at)}</span>}</div>
                  <Code>{d.compiled[b.backend] ?? "# not compiled for this backend yet"}</Code>
                </div>
              ))}
            </div>
          </Panel>
        </div>
        <div className="space-y-6">
          <Panel title="Backtest" meta="30-day dry run before deploy">
            <div className="px-5 pb-5">
              {d.backtestCount === null ? <p className="text-[13px] text-muted">Core rules are backtested per tenant at adoption time.</p> : (
                <>
                  <div className={"num text-[32px] font-semibold tracking-tight leading-none " + (d.backtestCount > 20 ? "text-ember" : "text-signal")}>{d.backtestCount}</div>
                  <div className="text-[12.5px] text-muted mt-1.5">expected findings over 30 days of {t?.name} telemetry</div>
                  {d.backtestCount > 20 && <p className="text-[12.5px] text-ember mt-3 leading-relaxed">High expected volume. Consider tuning before approving the deploy.</p>}
                  <div className="text-[12px] text-faint mt-3">Last run {d.backtestAt && fmtDateTime(d.backtestAt)}</div>
                </>
              )}
            </div>
          </Panel>
          <Panel title="Details">
            <div className="px-5 pb-5">
              <KV rows={[
                ["Rule id", <span key="i" className="mono text-[12.5px]">{d.id}</span>],
                ["Log source", d.logsource],
                ["Technique", <span key="t" className="mono text-[12.5px]">{d.technique}</span>],
                ["Source hunt", d.sourceHunt ? <Link key="h" href={`/hunts/${d.sourceHunt}`} className="text-ice mono text-[12.5px]">{d.sourceHunt}</Link> : "—"],
                ["Updated", fmtDateTime(d.updatedAt)],
              ]} />
            </div>
          </Panel>
          <Panel title="Deploy guardrails" quiet>
            <ul className="px-5 pb-5 text-[12.5px] text-muted space-y-1.5 leading-relaxed">
              <li>Merge to the Sigma PR is a human action. No service account can merge.</li>
              <li>Deploys require approval, always synchronous, always explicit.</li>
              {t?.slug === "acme" && <li className="text-ember">Acme requires Detection Engineer plus the named IT contact to co-sign production Splunk deploys.</li>}
            </ul>
          </Panel>
        </div>
      </div>
    </div>
  );
}
